application: curtisautery
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin
  static_files: static/admin.html
  upload: static/admin.html
  login: admin
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/
  static_dir: static

- url: /(load|post|init|flush|preview|info|verify)
  script: _go_app
  login: admin

- url: /(.*)
  script: _go_app
